local _,rematch = ...
local L = rematch.localization

if GetLocale()=="zhCN" then
-- cards\petCard.lua
L["Undo"] = "撤销"
L["Delete Notes"] = "删除注释"
L["Do you want to delete notes for team %s\124r?"] = "是否要删除队伍%s\124r的注释?"
L["Do you want to delete notes for pet %s%s\124r?"] = "是否要删除宠物%s%s\124r的注释?"
L["Don't Ask When Deleting Notes"] = "删除注释时不询问"

-- cards\petCard.lua
L["Pet Card"] = "宠物卡片"
L["Damage\nTaken"] = "承受\n伤害"
L["from"] = "来自"
L["abilities"] = "技能"
L["Possible Breeds"] = "可能的品种"
L["Stats as \124cff0070ddRare\124r level 25"] = "作为\124cff0070dd稀有\124r25级的属性"
L["All breed data pulled from %s%s\124r"] = "所有品种数据来自%s%s\124r"
L["No known breeds :("] = "无已知品种:("
L["When this team loads, your current leveling pet will go in this spot."] = "加载队伍时, 当前升级宠物会占据此位置."
L["When this team loads, this spot will be ignored."] = "加载队伍时, 此位置将被忽略."
L["When this team loads, a random high level pet will go in this spot."] = "加载队伍时, 随机高等级宠物会占据此位置."
L["The pets for this target are not recorded due to this target not being notable."] = "由于目标不可记录, 未保存对应宠物."
L["Hold [%s] to view more about this pet."] = "按住[%s]查看此宠物详细信息."
L["This is an opponent pet."] = "这是敌方宠物."

-- cards\petCardStats.lua
L["Revoked"] = "已撤销"
L["This pet has been revoked, which means Blizzard withdrew your ability to use this pet.\n\nThis commonly happens when a pet no longer meet a condition for ownership, such as the Core Hound Pup requiring an authenticator attached to the account."] = "该宠物已被撤销, 意味着暴雪收回了使用权限.\n\n常见于不再满足拥有条件的情况, 如熔火恶犬宝宝需要战网安全令."
L["Can't Summon"] = "无法召唤"
L["Expansion"] = "资料片"
L["The World of Warcraft expansion this pet is from."] = "该宠物所属的魔兽世界资料片."
L["New Pet"] = "新宠物"
L["This pet was recently added to your collection."] = "该宠物最近加入你的收藏."
L["This is the pet marker you've chosen for this pet. You can change the marker from the pet's right-click menu."] = "这是你为宠物设置的标记. 可通过右键菜单修改."
L["Slotted"] = "已装备"
L["This pet is currently slotted in one of the three battle pet slots."] = "该宠物当前装备在战斗宠物栏位中."
L["Favorite"] = "最爱"
L["This pet is marked as a favorite from its right-click menu."] = "该宠物已通过右键菜单标记为最爱."
L["Leveling"] = "升级中"
L["This pet is in Rematch's leveling queue."] = "该宠物在Rematch升级队列中."
L["Breed"] = "品种"
L["Determines how stats are distributed. All breed data is pulled from your installed %s%s\124r addon."] = "决定属性分配方式. 所有品种数据来自已安装的%s%s\124r插件."
L["Teams"] = "队伍"
L["%s Click to find all teams that include this specific pet."] = "%s点击查找包含此宠物的所有队伍."
L["%d Teams"] = "%d个队伍"
L["Not Tradable"] = "不可交易"
L["This pet cannot be caged or given to others."] = "该宠物无法放入笼中或交易."
L["No Trade"] = "禁止交易"
L["Unique"] = "唯一"
L["Only one copy of this pet can be owned at a time."] = "同一时间只能拥有一个该宠物."
L["Strongest Vs"] = "克制"
L["These are the pet types this pet is strongest against. One or more of this pet's attack abilities will deal extra damage to these pet types."] = "该宠物对以下类型有额外伤害."
L["vs "] = "vs "
L["Species ID"] = "物种ID"
L["All versions of this pet share this unique identifying number."] = "该宠物的所有版本共享此唯一标识号."
L["%s Click to search for all versions of this pet."] = "%s点击搜索该宠物的所有版本."

-- chrome\bottombar.lua
L["Save As"] = "另存为"
L["Rematch"] = "Rematch"
L["Remove Rematch From Journal"] = "从日志移除Rematch"
L["Uncheck this to restore the default pet journal.\n\nYou can still use Rematch in its standlone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "取消勾选以恢复默认宠物日志.\n\n仍可通过快捷键, /rematch命令或小地图按钮使用独立窗口."
L["You can also double-click a pet to summon or dismiss it."] = "双击宠物可召唤/解散."
L["Save As..."] = "另存为..."
L["Save the currently loaded pets to a new team."] = "将当前宠物保存为新队伍."
L["Quickly save the currently loaded pets and abilities to the loaded team."] = "快速保存当前宠物和技能到已加载队伍."

-- chrome\chromeMixins.lua
L["%s%d %s"] = "%s%d %s"
L["Team"] = "队伍"

-- chrome\minimap.lua
L["%s Toggle Window\n%s Load Favorite Team"] = "%s切换窗口\n%s加载最爱队伍"
L["Favorite Teams"] = "最爱队伍"
L["%sNo favorite teams :("] = "%s没有最爱队伍:("

-- chrome\toolbar.lua
L["UNIQUE_PETS"] = "唯一宠物"
L["TOTAL_PETS"] = "总宠物"
-- L["Unique Pets: %s%d\124r\nTotal Pets: %s%d\124r%s"] = nil
L["\n\n%s Click for details"] = "\n\n%s点击查看详情"

-- chrome\toolbarButtons.lua
L["All pets are at full health."] = "所有宠物生命值已满."
L["Pet Level %d %s"] = "宠物等级%d%s"
L["%s Dismiss Pet"] = "%s解散宠物"
L["Summon Random Pet"] = "召唤随机宠物"
L["Random favorite pet"] = "随机最爱宠物"
L["Random from all pets"] = "全部宠物中随机"
L["%s%s"] = "%s%s"

-- dialogs\dialogMixins.lua
L["Level"] = "等级"
L["Min:"] = "最小:"
L["Max:"] = "最大:"
L["Health"] = "生命值"
L["%s %s or %s"] = "%s %s或%s"
L["Allow any"] = "允许任意"
L["Expected Damage Taken:"] = "预计承受伤害:"
L["Minimum Level"] = "最低等级"
L["This is the minimum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 4.33 is level 4 with 33% xp towards level 5."] = "升级宠物的最低等级限制.\n\n可接受小数, 如4.33表示4级33%经验."
L["Maximum Level"] = "最高等级"
L["This is the maximum level preferred for a leveling pet.\n\nLevels can be partial amounts. Level 23.45 is level 23 with 45% xp towards level 24."] = "升级宠物的最高等级限制.\n\n可接受小数, 如23.45表示23级45%经验."
L["Minimum Health"] = "最低生命值"
L["The queue will prefer leveling pets with at least this much health (adjusted by expected damage taken if any chosen)."] = "优先选择至少拥有此生命值的宠物(根据预期伤害调整)."
L["Maximum Health"] = "最高生命值"
L["This is the maximum health preferred for a leveling pet."] = "升级宠物的最高生命值限制."
L["Allow low-health and low-level Magic or Mechanical pets to ignore the Minimum Health or Level, since their racials allow them to often survive a hit that would ordinarily kill them."] = "允许低生命/低等级的魔法/机械宠物忽略最低要求, 因其种族技能常可承受致命一击."
L["Expected Damage Taken"] = "预期承受伤害"
L["The minimum health of pets can be adjusted by the type of damage they are expected to receive."] = "可根据预期伤害类型调整最低生命值要求."
L["Damage Expected: %s"] = "预期伤害: %s"
L["Minimum Health: %d"] = "最低生命值: %d"
L["  For %s pets: \124cffffffff%d"] = "  对于%s宠物: \124cffffffff%d"
L["Search Icons"] = "搜索图标"
L[" Add"] = " 添加"
L[" Delete"] = " 删除"
L[" Up"] = " 上"
L[" Down"] = " 下"
L["Delete"] = "删除"
L["Up"] = "上"
L["Down"] = "下"
L["Choose a group for this team"] = "为队伍选择分组"
L["Group:"] = "分组:"
L["Wins:"] = "胜利:"
L["Losses:"] = "失败:"
L["Draws:"] = "平局:"
L["Total Battles: %s%s"] = "总战斗: %s%s"
L["None"] = "无"
L["Win Rate: %d%%"] = "胜率: %d%%"
L["Include Preferences"] = "包含偏好"
L["Include Notes"] = "包含注释"
L["When teams/groups share the same name:"] = "当队伍/分组重名时:"
L["Create a new copy"] = "创建新副本"
L["Overwrite existing one"] = "覆盖现有"
L["Won"] = "胜"
L["Lost"] = "负"
L["Draw"] = "平"
L["%s%d\124r Battles for %s%d\124r Teams"] = "%s%d\124r场战斗(%s%d\124r支队伍)"

-- dialogs\importDialog.lua
L["Import Teams"] = "导入队伍"
L["Load"] = "加载"
L["Press Ctrl+V to paste from clipboard"] = "按Ctrl+V粘贴剪贴板内容"
L["Prioritize Breed For Imports"] = "导入时优先考虑品种"
L["When importing teams, prefer pets that match the breed even if higher levels of other breeds are available."] = "即使有其他高等级品种也优先匹配指定品种."
L["Only Load This Team"] = "仅加载此队伍"
L["This will only load the team and not save it.\n\nThis is for importing teams you intend to use just once. You can still save the team afterwards if you want to keep it."] = "仅临时加载不保存.\n\n适用于一次性使用的队伍, 后续仍可手动保存."
L["This is not a valid team import"] = "无效的队伍导入数据"
L["Groups to import"] = "要导入的分组"
L["Teams to import"] = "要导入的队伍"
L["Names already used"] = "名称已被使用"
L["Some teams or groups have names already used"] = "部分队伍/分组名称重复"
L["This team has the same name as an existing team"] = "队伍名称与现有队伍重复"
L["Teams with existing name"] = "存在重名队伍"
L["Some teams have the same name as existing teams"] = "部分队伍名称已存在"

-- dialogs\saveDialog.lua
L["Save Team"] = "保存队伍"
L["Overwrite Team"] = "覆盖队伍"
L["New Copy"] = "新建副本"
L["Overwrite"] = "覆盖"
L["Another team already has this name. Overwrite it or create a new copy?"] = "已有同名队伍, 覆盖还是新建副本?"
L["Old %s"] = "旧%s"
L["New %s"] = "新%s"
L["Saving Loaded Team"] = "保存加载的队伍"
L["Save team?"] = "保存队伍?"
L["Pets have changed. Confirm you want to update the team with these new pets."] = "宠物已变更, 确认更新队伍."
L["Update team from this:"] = "从以下内容更新队伍:"
L["To this:"] = "更新为:"
L["Sending Team"] = "发送队伍"
L["Not yet implemented\n\nSending teams directly to other Rematch users will be added later in the beta."] = "尚未实现\n\n直接发送队伍给其他Rematch用户的功能将在后续测试版添加."
L["Targets"] = "目标"
L["Preferences"] = "偏好设置"
L["Wins"] = "胜利"
L["Create a new copy of this team"] = "创建此队伍的新副本"
L["Another team has this name."] = "存在同名队伍."
L["Edit Team"] = "编辑队伍"
L["Receiving Team"] = "接收队伍"
L["Name:"] = "名称:"
L["New Team"] = "新队伍"
L["Someone sent you a group!"] = "有人发送给你一个分组!"
L["Leveling Preferences"] = "升级偏好"
L["Leveling preferences override which pets are picked first in the leveling queue. All criteria are optional."] = "升级偏好决定队列优先级, 所有条件均为可选."
L["Battles Won By This Team"] = "该队伍获胜次数"

-- dialogs\scriptFilter.lua
L["Unnamed Pets"] = "未命名宠物"
L["-- Collected pets that still have their original name.\n\nreturn petInfo.isOwned and not petInfo.customName"] = "-- 仍保留原始名称的已收集宠物.\n\nreturn petInfo.isOwned and not petInfo.customName"
L["Partially Leveled"] = "部分升级"
L["-- Pets that have earned some xp in battle.\n\nreturn petInfo.xp and petInfo.xp>0"] = "-- 在战斗中获取过经验的宠物.\n\nreturn petInfo.xp and petInfo.xp>0"
L["Pets Without Rares"] = "无稀有版本宠物"
L["-- Collected battle pets that have no rare version.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif petInfo.canBattle and petInfo.isOwned and not rares[speciesID] then\n  return true\nend"] = "-- 没有稀有版本的战斗宠物.\n\nif not rares then\n  rares = {}\n  for petID in AllPetIDs() do\n    if select(5,C_PetJournal.GetPetStats(petID))==4 then\n      rares[C_PetJournal.GetPetInfoByPetID(petID)]=true\n    end\n  end\nend\n\nif petInfo.canBattle and petInfo.isOwned and not rares[speciesID] then\n  return true\nend"
L["Polished Pet Charms"] = "抛光宠物符咒师"
L["-- Pets with Polished Pet Charms in their source.\n\nreturn (petInfo.sourceText or \"\"):match(\"item:163036\") and true"] = "-- 来源包含抛光宠物符咒师.\n\nreturn (petInfo.sourceText or \"\"):match(\"item:163036\") and true"
L["Script Filter"] = "脚本过滤器"
L["Test"] = "测试"
L["New Script Filter"] = "新建脚本过滤器"
L["Script Name:"] = "脚本名称:"
L["Script filters create custom filters with Lua code.\nSee /docs/scriptfilters.txt for more information."] = "通过Lua代码创建自定义过滤器.\n详见/docs/scriptfilters.txt"
L["Delete Script Filter"] = "删除脚本过滤器"
L["\nAre you sure you want to delete the script filter named %s%s\124r?\n\n"] = "\n确定要删除名为%s%s\124r的脚本过滤器吗?\n\n"
L["Script Filter Error"] = "脚本过滤器错误"
L["%sThe script filter just loaded has the following error and will not be used:"] = "%s加载的脚本过滤器存在以下错误, 将不会被使用:"
L["line "] = "行 "

-- dialogs\summaryDialog.lua
L["Unique Pets In the Journal"] = "日志唯一宠物"
L["Total Collected Pets"] = "总收集宠物"
L["Unique Collected Pets"] = "已收集唯一宠物"
L["Pets Not Collected"] = "未收集宠物"
L["Percent Collected"] = "收集百分比"
L["Max Level Pets"] = "满级宠物"
L["Average Pet Level"] = "平均宠物等级"
L["Rare Quality Pets"] = "稀有品质宠物"
L["Pets In Teams"] = "队伍中的宠物"
L["Pet Collection"] = "宠物收集"
L["Total"] = "总计"
L["Pets Collected"] = "已收集宠物"
L["Pets At Max Level"] = "满级宠物数量"
L["Duplicate Collected Pets"] = "重复收集宠物"
L["Average Battle Pet Level"] = "战斗宠物平均等级"
L["There are %s%d\124r unique pets in the journal"] = "日志中有%s%d\124r种唯一宠物"
L["You've collected %s%.1f%%\124r of them"] = "已收集%s%.1f%%\124r"

-- info\petInfo.lua
L["Unknown"] = "未知"
L["Leveling Pet"] = "升级宠物"
L["Ignored Pet"] = "被忽略的宠物"
L["Random %s"] = "随机%s"
L["Random Pet"] = "随机宠物"
L["Empty Pet Slot"] = "空宠物栏位"
L["Not Notable"] = "不可记录"

-- info\targetData.lua
L["Menagerie"] = "宠物小窝"
L["Garrison"] = "要塞"
L["Beasts of Fable"] = "寓言之兽"

-- info\targetInfo.lua
L["No Target"] = "无目标"
L["%s (npc id %d)"] = "%s(NPC ID %d)"

-- layout\definitions.lua
L["TAB_PETS"] = "宠物"
L["TAB_TEAMS"] = "队伍"
L["TAB_TARGETS"] = "目标"
L["TAB_QUEUE"] = "队列"
L["TAB_OPTIONS"] = "选项"

-- layout\frame.lua
L["Rematch can't be summoned during combat. Try again later"] = "战斗中无法召唤Rematch, 请稍后再试"

-- layout\journal.lua
L["Use Rematch In Journal"] = "在日志中使用Rematch"
L["Check this to restore Rematch to the journal.\n\nYou can always use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "勾选以在日志中恢复Rematch界面.\n\n仍可通过快捷键, /rematch命令或小地图按钮使用独立窗口."

-- main\constants.lua
L["Toggle Rematch"] = "切换Rematch"
L["Rematch Team Notes"] = "Rematch队伍注释"
L["Journal Is Locked"] = "日志已锁定"
L["Wrong Faction"] = "阵营错误"
L["Wrong Covenant"] = "盟约错误"
L["\124cffff2020Retrieving data..."] = "\124cffff2020正在检索数据..."
L["Random Team"] = "随机队伍"

-- main\slash.lua
L["Reset Everything"] = "重置所有"
L["Reset everything?"] = "确定要重置所有内容?"
L["This will wipe all settings, teams, queue, etc (absolutely everything), and then reload the UI to start Rematch from scratch."] = "将清除所有设置, 队伍, 队列等(全部内容), 并重载界面重新开始."
L["Warning: This cannot be undone!"] = "警告: 该操作不可逆!"
L["Delete All Teams"] = "删除所有队伍"
L["Delete all teams?"] = "确定删除所有队伍?"
L["This will wipe all teams and groups.\n\nAre you sure you want to %sDELETE\124r all teams and groups permanently?"] = "将删除所有队伍和分组.\n\n确定要永久%s删除\124r所有队伍和分组吗?"
L["Usage: Target an npc to create data for, enter a pet battle, and once in battle with opponent pets displayed, enter:\n\124cffffffff/rematch targetdata"] = "用法: 选中目标NPC后进入宠物对战, 当对手宠物显示时输入:\n\124cffffffff/rematch targetdata"
L["The team named \"%s\" can't be found."] = "未找到名为\"%s\"的队伍."

-- menus\loadoutMenu.lua
L["Put Leveling Pet Here"] = "放置升级宠物"
L["Stop Leveling This Slot"] = "停止升级此栏位"
L["Put Random Pet Here"] = "放置随机宠物"
L["Stop Randomizing This Slot"] = "停止随机此栏位"
L["Ignore This Slot"] = "忽略此栏位"
L["Stop Ignoring This Slot"] = "停止忽略此栏位"
L["Any Type"] = "任意类型"
L["Set Notes"] = "设置注释"
L["Find Similar"] = "查找相似"
L["Find Teams"] = "查找队伍"
L["Battle Pet Slot %d"] = "战斗宠物栏位%d"

-- menus\menus.lua
L["Print TeamID"] = "打印队伍ID"

-- menus\petFilterMenu.lua
L["In addition to the filters in this menu, you can further refine the pet list with the search box. Some search examples:\n\nPets: %sBlack Tabby\124r\nZones: %sSilithus\124r\nAbilities: %sSandstorm\124r\nText in abilities: %sBleed\124r\nLevels: %slevel=21-23\124r\nStats: %sspeed>300\124r\n\nSearches in \"quotes\" will limit results to only complete matches.\n\nSearch results will be sorted by relevance unless the option %sDon't Sort By Relevance\124r is checked in the Options tab."] = "除了菜单中的筛选, 还可以通过搜索框进一步过滤宠物列表. 搜索示例:\n\n宠物名: %s黑纹灰猫\124r\n区域: %s希利苏斯\124r\n技能: %s沙尘暴\124r\n技能描述: %s流血\124r\n等级: %slevel=21-23\124r\n属性: %sspeed>300\124r\n\n使用\"引号\"包裹的搜索词将精确匹配.\n\n搜索结果默认按相关性排序, 除非在选项页取消勾选%s不按相关性排序\124r."
L["In filter menus, checkbox groups assume if nothing is checked you want to view all choices.\n\nYou can also:\n\n%s[Shift]+Click\124r to check all except the box clicked.\n\n%s[Alt]+Click\124r to uncheck all except the box clicked."] = "在多选筛选项中， 未勾选时默认显示全部.\n\n操作技巧:\n\n%s[Shift]+点击\124r反选当前项.\n%s[Alt]+点击\124r单选当前项."
L["Only Favorites"] = "仅最爱"
L["Strong Vs"] = "克制"
L["Tough Vs"] = "抵抗"
L["Pet Marker"] = "宠物标记"
L["Script"] = "脚本"
L["Favorite Filters"] = "最爱筛选"
L["Export Pets"] = "导出宠物"
L["Help"] = "帮助"
L["Pet Filter"] = "宠物筛选"
L["Reset All"] = "重置全部"
L["Checkbox Groups"] = "复选框组"
L["Low Level (1-7)"] = "低级(1-7)"
L["Mid Level (8-14)"] = "中级(8-14)"
L["High Level (15-24)"] = "高级(15-24)"
L["Max Level (25)"] = "满级(25)"
L["Without Any 25s"] = "无满级宠物"
L["Moveset Not At 25"] = "技能未满级"
L["All breed data is pulled from your installed %s%s\124r addon.\n\nThe breed \"New\" means the pet has no breed data. Keep your breed addon up to date to ensure it has the most recent breed data."] = "品种数据来自%s%s\124r插件.\n\n\"新\"表示无品种数据, 请及时更新插件."
L["Not Leveling"] = "未在升级"
L["Tradable"] = "可交易"
L["Can Battle"] = "可战斗"
L["Can't Battle"] = "不可战斗"
L["One Copy"] = "一份"
L["Two+ Copies"] = "两份以上"
L["Three+ Copies"] = "三份以上"
L["In A Team"] = "在队伍中"
L["Not In A Team"] = "不在队伍中"
L["Unique Moveset"] = "独有技能组"
L["Shared Moveset"] = "共享技能组"
L["Current Zone"] = "当前区域"
L["Hidden Pets"] = "隐藏宠物"
L["Has Notes"] = "有注释"
L["Then Sort By"] = "然后按下述排序"
L["Reverse Sort"] = "反向排序"
L["Favorites First"] = "最爱优先"
L["You can filter to a specific range of stats too. For example, search for:\n\n%shealth>500\124r\nor\n%sspeed=200-300\124r\n\nThe sort order is not ordinarily reset when filters are reset. The option %sReset Sort With Filters\124r in the Options tab will reset the sort when you reset the filters."] = "可通过特别范围筛选, 例如：\n\n%shealth>500\124r\n或\n%sspeed=200-300\124r\n\n重置筛选时排序不会自动重置, 需在选项中启用%s重置时恢复默认排序\124r."
L["Finally Sort By"] = "最终排序"
L["Save Favorite Filter"] = "保存最爱筛选"
L["Save this Favorite Filter?"] = "保存该筛选组合?"
L["Filters: %s%s\124r\n\nEnter a new name for this Favorite Filter:"] = "筛选条件: %s%s\124r\n\n输入新的筛选组合名称: "
L["Filters: %s%s\124r\n\nEnter a name for this new Favorite Filter:"] = "筛选条件: %s%s\124r\n\n输入新筛选组合名称: "
L["Delete Favorite Filter"] = "删除最爱筛选"
L["\nAre you sure you want to delete the filter named %s%s\124r?\n\nFilters: %s%s\n\n"] = "\n确定要删除%s%s\124r筛选组合吗?\n\n条件: %s%s\n\n"
L["Press Ctrl+C to copy to clipboard\n\n%sThese are pets currently listed. Adjust the filters to limit which to include."] = "按Ctrl+C复制到剪贴板\n\n%s当前显示的宠物列表. 调整筛选以限制范围."
L["Export Simple Pet List"] = "导出简易宠物列表"
L["Rename Pet Marker"] = "重命名宠物标记"
L["Enter a new name"] = "输入新名称"
L["Script Filters"] = "脚本筛选"
L["New Script"] = "新建脚本"
L["Script filters are a way to create new pet filters with Lua code.\n\nSome knowledge of Lua is helpful to create them. See docs/scriptfilters.txt for more information."] = "通过Lua代码创建自定义筛选.\n\n需要基础Lua知识, 详见docs/scriptfilters.txt."
L["Save Filter"] = "保存筛选"
L["A filter must be active before it can be saved."] = "需先激活筛选条件才能保存"
L["Total Pets: %d"] = "总宠物: %d"
L["Distinct Pets: %d"] = "唯一宠物: %d"
L["Species Name,Custom Name,Type,Collected,Favorite,Level,Rarity"] = "物种名称, 自定义名称, 类型, 已收集, 最爱, 等级, 品质"
L[",Breed"] = ",品种"

-- menus\petMenu.lua
L["Find Moveset"] = "查找技能组"
L["Slotted pets can't be released."] = "已装备的宠物无法放生."
L["Pet name too long.\nMaximum 16 characters."] = "名称过长.\n最多16个字符."
L["Invalid name.\nNo numbers allowed."] = "无效名称.\n不可包含数字."
L["Hide Pet"] = "隐藏宠物"
L["Hide this pet?"] = "隐藏该宠物?"
L["Are you sure you want to hide all versions of %s%s\124r?\n\n%sHidden pets will not show up in the pet list or searches. You can view or unhide these pets from the 'Other' pet filter."] = "确定要隐藏%s%s\124r的所有版本?\n\n%s隐藏的宠物不会出现在列表或搜索结果中. 可在'其他'筛选项中查看."
L["Don't Ask When Hiding Pets"] = "隐藏宠物时不询问"
L["Release this pet?"] = "放生该宠物?"
L["Once released, this pet is gone forever!"] = "放生后将永久失去!"
L["This pet is used in teams! "] = "该宠物存在于队伍中!"
L["Cage this pet?"] = "放入笼中?"
L["Don't Ask When Caging Pets"] = "放入笼中时不询问"
L["This pet is used in teams!"] = "该宠物存在于队伍中!"
L["Show Pet"] = "显示宠物"
L["Injured pets cannot be caged."] = "受伤宠物无法放入笼中."
L["Slotted pets cannot be caged."] = "已装备宠物无法放入笼中."
L["Remove from Leveling Queue"] = "移出升级队列"
L["Add to Leveling Queue"] = "加入升级队列"

-- menus\queueMenu.lua
L["Sort by:"] = "排序方式:"
L["Ascending Level"] = "等级升序"
L["Median Level"] = "中位等级"
L["Descending Level"] = "等级降序"
L["In Teams First"] = "队伍优先"
L["Rares First"] = "稀有优先"
L["Active Sort"] = "动态排序"
L["The queue will automatically order pets by the sort criteria in the menu options above. The order of pets may automatically change as they gain xp or get added/removed from the queue.\n\nYou cannot manually change the order of pets and still keep the queue actively sorted."] = "队列会根据所选排序规则自动调整顺序. 当宠物获得经验或添加/移除时顺序可能变化.\n\n启用时无法手动调整顺序."
L["Pause Preferences"] = "暂停偏好"
L["Suspend all criteria from default, team and group preferences.\n\nWhile preferences are paused, the top-most pet in the queue will be chosen if it can be loaded."] = "暂停所有升级偏好设置.\n\n暂停时优先选择队列顶部的宠物."
L["Fill Queue"] = "填充队列"
L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, that you don't have a level 25 copy or one in the queue already."] = "为筛选出的未满级宠物(且队列中不存在)各添加一个到队列."
L["Fill Queue More"] = "更多填充"
L["Fill the leveling queue with one of each version of a pet that can level from the filtered pet list, regardless whether you have any at level 25 or one in the queue already."] = "强制填充所有可升级宠物到队列(忽略已有满级或队列存在)."
L["Empty Queue"] = "清空队列"
L["Remove all pets from the leveling queue."] = "移除队列中所有宠物."
L["Export Queue"] = "导出队列"
L["Export all pets in the leveling queue for later importing.\n\n%sNote\124r: Rematch will make a best guess what to import, but there's no guarantee the exact same pets will import, especially after they've leveled. This works best without many duplicates."] = "导出当前队列宠物.\n\n%s注意\124r: 导入时可能无法完全还原, 此功能在没有太多重复的情况下效果最佳."
L["Import Queue"] = "导入队列"
L["Import pets to the queue that have been previously exported.\n\n%sNote\124r: Rematch will make a best guess what to import, but there's no guarantee the exact same pets will import, especially after they've leveled. This works best without many duplicates."] = "导入先前导出的队列宠物.\n\n%s注意\124r: 导入时可能无法完全还原, 此功能在没有太多重复的情况下效果最佳."
L["This is the leveling queue. Drag pets you want to level here.\n\nRight click any of the three battle pet slots and choose 'Put Leveling Pet Here' to mark it as a leveling slot you want controlled by the queue.\n\nWhile a leveling slot is active, the queue will fill the slot with the top-most pet in the queue. When this pet reaches level 25 (gratz!) it will leave the queue and the next pet in the queue will take its place.\n\nTeams saved with a leveling slot will reserve that slot for future leveling pets."] = "升级队列说明:\n1. 拖动宠物至此\n2. 右键战斗栏位设为'升级栏位'\n3. 队列会自动填充栏位\n4. 满级后自动替换下一宠物\n5. 队伍保存时会保留升级栏位"
L["Move To Top Of Queue"] = "移至队列顶部"
L["Move Pet In Queue"] = "移动队列宠物"
L["Move To End Of Queue"] = "移至队列末尾"
L["Empty queue?"] = "确定清空队列?"
L["Are you sure you want to remove all pets from the leveling queue?"] = "确定移除队列中所有宠物?"
L["Add these pets to the queue?"] = "确定添加这些宠物到队列?"
L["More"] = "更多"
L["This will add %s%s\124r pets to the leveling queue."] = "将添加%s%s\124r个宠物到队列."
L["Don't Ask When Filling Queue"] = "填充队列时不询问"
L["This is a lot of pets. You can be more selective by filtering pets."] = "宠物数量较多, 建议使用筛选."
L["Active Sort Enabled"] = "动态排序已启用"
L["Turn off Active Sort and move pet?"] = "是否关闭动态排序并移动宠物?"
L["%s is already in the queue and Active Sort is enabled."] = "%s已在队列中且动态排序已启用."
L["The queue controls the order of pets while it's actively sorted.\n\nTo move this pet within the queue, Active Sort needs to be turned off."] = "队列在动态排序时自动控制宠物顺序.\n\n要手动移动宠物需先关闭动态排序."
L["Don't Ask To Stop Active Sort"] = "关闭动态排序时不询问"
L["Remove From Queue"] = "移出队列"
L["Remove %s from the leveling queue?"] = "是否将%s移出升级队列?"
L["Don't Ask For Queue Removal"] = "移出队列时不询问"
L["Import"] = "导入"
L["This is not a valid queue import"] = "无效的队列导入数据"
L["Pets to add to queue"] = "待添加至队列的宠物"
L["Pets already in queue"] = "已在队列中的宠物"
L["Pets that can't level"] = "无法升级的宠物"
L["Invalid pets"] = "无效宠物"

-- menus\targetMenu.lua
L["Edit Target"] = "编辑目标"
L["Load Random Pets"] = "加载随机宠物"
L["Load Team"] = "加载队伍"
L["These are the teams saved for %s."] = "这是为%s保存的队伍列表."
L["The topmost team is the preferred team to load when you interact with this target."] = "顶部队伍为优先加载的默认队伍."
L["No teams :("] = "无可用队伍:("

-- menus\teamMenu.lua
L["Edit Group"] = "编辑分组"
L["Move Group"] = "移动分组"
L["Delete Group"] = "删除分组"
L["Export Group"] = "导出分组"
L["Unload Team"] = "卸载队伍"
L["Move Team"] = "移动队伍"
L["Load Target"] = "加载目标"
L["Share"] = "分享"
L["Delete Team"] = "删除队伍"
L["Plain Text"] = "纯文本"
L["Export Team"] = "导出队伍"
L["Send Team"] = "发送队伍"
L["Sending teams is disabled due to Disabling Sharing in options.\n\nYou can still export and import teams, however."] = "分享功能已禁用, 无法发送队伍.\n仍可通过导入/导出交换队伍."
L["Create New Group"] = "创建新分组"
L["Team Herder"] = "队伍管理"
L["Backup All Teams"] = "备份所有队伍"
L["New Group"] = "新建分组"
L["Group"] = "分组"
L["Icon"] = "图标"
L["Group Name:"] = "分组名称:"
L["Sort:"] = "排序:"
L["By Name"] = "按名称"
L["Sort By Name"] = "名称排序"
L["Sort teams in this group alphabetically."] = "按字母顺序排列分组内队伍."
L["By Wins"] = "按胜场"
L["Sort By Wins"] = "胜场排序"
L["Sort teams in this group by how many times the team has won, if win records are tracked."] = "按队伍胜场数排序(需启用胜场追踪)."
L["Custom Sort"] = "自定义排序"
L["Sort teams in this group manually. New teams to this group are added to the end."] = "手动排序分组内队伍, 新队伍默认添加至末尾."
L["Show Tab For This Group"] = "显示分组标签页"
L["Up to %d groups can be chosen to display as tabs along the right side of the Rematch window.\n\n%s%d of %d\124r possible tabs are shown."] = "最多可选择%d个分组显示为右侧标签页.\n当前显示%s%d/%d\124r个标签页."

-- panels\loadedTargetPanel.lua
L["Load a set of random high level pets. If the recent target's pets are known, random pets are preferred if they are strong vs and tough vs the opponent pets."] = "加载随机高等级宠物(优先选择克制敌方宠物的类型)."
L["Add or remove teams from this target, or change the order of teams for this target."] = "为目标添加/移除队伍或调整队伍顺序."
L["Save New Team"] = "保存新队伍"
L["Create a new team for this target with the currently loaded pets."] = "根据当前宠物创建针对此目标的新队伍."
L["Load the team saved to this target."] = "加载为此目标保存的队伍."
L["Save"] = "保存"

-- panels\loadedTeamPanel.lua
L["Counter to %s"] = "克制%s"

-- panels\loadoutPanel.lua
L["When this team loads, a pet from the leveling queue will go in this spot."] = "加载队伍时, 升级队列中的宠物会占据此位置."
L["Ignored Slot"] = "忽略的栏位"

-- panels\optionsList.lua
L["All Options"] = "所有选项"
L["Interaction Options"] = "交互选项"
L["On Target"] = "选中目标时"
L["On Mouseover"] = "鼠标悬停时"
L["On Soft Interact"] = "软交互时"
L["Always Interact"] = "始终交互"
L["The default behavior is to perform the target or mouseover interaction once until you interact with another NPC with a saved team. Check this to always interact with NPCs that have a saved team not already loaded."] = "默认仅对首个有保存队伍的目标生效, 勾选后会对所有未加载队伍的目标生效."
L["Prefer Uninjured Teams"] = "优先无受伤队伍"
L["When you interact with an NPC that has more than one team saved to it, choose the team with no injured pets instead of the topmost team for the target. On Prompt To Load and Show Minimized Window options where you can choose which team to load, start with the healthiest team."] = "存在多个队伍时优先选择无受伤宠物的队伍."
L["Show Window After Loading"] = "加载后显示窗口"
L["When a team is loaded from an interaction (target or mouseover) and the Rematch window is not on screen, summon the standalone Rematch window."] = "通过交互加载队伍时自动弹出独立窗口."
L["Only When Any Pets Injured"] = "仅当有宠物受伤时"
L["If a team is loaded but no pets are injured, don't summon the Rematch window."] = "队伍中无受伤宠物时不弹出窗口."
L["Standalone Window Options"] = "独立窗口选项"
L["Anchor To"] = "锚点位置"
L["Use Custom Scale"] = "使用自定义缩放"
L["Keep Window On Screen"] = "保持窗口可见"
L["Don't hide the standalone window when the ESCape key is pressed or most other times it would hide, such as going to the game menu."] = "按ESC键时不隐藏窗口."
L["Even For Pet Battles"] = "宠物对战时保持显示"
L["Keep the standalone window on the screen even when you enter pet battles."] = "进入宠物对战后仍显示窗口."
L["Even Across Sessions"] = "跨会话保持"
L["If the standalone window was on screen when logging out, automatically summon it on next login."] = "下次登录时自动恢复窗口位置."
L["Don't Minimize With ESC Key"] = "按ESC不最小化"
L["Don't minimize the standalone window when the ESCape key (or game menu key) is pressed."] = "按ESC键不最小化窗口."
L["Don't Minimize With Panel Tabs"] = "切换标签页不最小化"
L["Don't let the Pets, Teams, Queue or Options tabs minimize the standalone window."] = "切换主标签页时不最小化窗口."
L["Lower Window Behind UI"] = "窗口置于界面后方"
L["Push the standalone window back behind other parts of the UI so other parts of the UI can appear ontop."] = "将窗口层级调低以免遮挡其他界面."
L["Show Pets Tab While Minimized"] = "最小化时显示宠物标签"
L["When the window has a Pets tab and is minimized, drop the Targets tab and keep the Pets tab visible."] = "最小化时保留宠物标签可见."
L["Show Window After Battle"] = "战后显示窗口"
L["Show the standalone Rematch window after leaving a pet battle."] = "离开宠物对战后自动显示窗口."
L["But Not After PVP Battle"] = "PVP战斗后除外"
L["Since pets don't remain injured in PVP battles, don't show the window when leaving a PVP battle."] = "PVP战斗后不自动显示窗口."
L["Appearance Options"] = "外观选项"
L["Compact Pet List"] = "紧凑宠物列表"
L["Display more pets in the pet list by using a more compact view of each pet."] = "通过更紧凑的视图在宠物列表中显示更多宠物."
L["Compact Team List"] = "紧凑队伍列表"
L["Display more teams in the team list by using a more compact view of each team."] = "通过更紧凑的视图在队伍列表中显示更多队伍."
L["Compact Target List"] = "紧凑目标列表"
L["Display more targets in the target list by using a more compact view of each target."] = "通过更紧凑的视图在目标列表中显示更多目标."
L["Compact Queue List"] = "紧凑队列列表"
L["Display more pets in the queue by using a more compact view of each pet."] = "通过更紧凑的视图在队列中显示更多宠物."
L["Hide Level At Max Level"] = "满级隐藏等级"
L["If a pet is level 25, don't show its level on the pet icon."] = "满级宠物图标不显示等级."
L["Hide Rarity Borders"] = "隐藏品质边框"
L["Don't color the icon border for pets you own in the same color as its rarity."] = "不按品质着色宠物图标边框."
L["Show Ability Numbers"] = "显示技能编号"
L["In the ability flyout, show the numbers 1 and 2 to help with the common notation such as \"Pet Name 122\" to know which abilities to use."] = "在技能弹出菜单中显示1和2编号, 辅助识别\"宠物名122\"等常用标记."
L["On Loaded Abilities Too"] = "已加载技能同样显示"
L["In addition to the flyouts, show the numbers 1 and 2 on loaded abilities."] = "在已加载的技能上也显示编号."
L["Color Pet Names By Rarity"] = "按品质着色宠物名"
L["Make the names of pets you own the same color as its rarity. Blue for rare, green for uncommon, etc."] = "已拥有宠物名称显示品质颜色(蓝/绿/灰等)."
L["Color Team Names By Group"] = "按分组着色队伍名"
L["Make team names colored the same as the colors you've chosen for the groups they belong to."] = "队伍名称显示所属分组的颜色."
L["Color Targets By Expansion"] = "按资料片着色目标"
L["Make notable target names colored after the expansion the target is from."] = "显著目标名称显示所属资料片颜色."
L["Behavior Options"] = "行为选项"
L["Card Speed"] = "卡片显示速度"
L["Choose how quickly you prefer the pet card and notes to be shown when you mouseover a pet or notes button."] = "选择鼠标悬停时宠物卡片/注释的弹出速度."
L["Tooltip Speed"] = "提示信息速度"
L["Collapse Lists With ESC Key"] = "ESC键折叠列表"
L["When the ESCape key (or game menu key) is pressed, collapse any expanded list--such as this options list, teams or targets."] = "按ESC键时折叠所有展开列表(如选项/队伍/目标列表)."
L["Toolbar Options"] = "工具栏选项"
L["Reverse Toolbar Buttons"] = "反转工具栏按钮顺序"
L["Reverse the order of the toolbar buttons (Revive Battle Pets, Battle Pet Bandages, Safari Hat, etc)."] = "反转工具栏按钮排列顺序(复活战斗宠物/战斗宠物绷带/狩猎帽等)."
L["Hide On Toolbar Right Click"] = "右键点击工具栏隐藏窗口"
L["When a toolbar button is used with a right click, dismiss the Rematch window after performing its action."] = "右键使用工具栏功能后自动关闭窗口."
L["Safari Hat Reminder"] = "狩猎帽提醒"
L["When a pet is loaded below max level, draw attention to the Safari Hat button, including summoning the window if it's not on screen."] = "加载未满级宠物时突出显示狩猎帽按钮."
L["Display Unique Pets Total"] = "显示唯一宠物总数"
L["Instead of Total Pets in the collections button at the topleft, display a total of Unique Pets."] = "左上角收藏按钮显示唯一宠物总数而非总数."
L["Pet Filter Options"] = "宠物筛选选项"
L["Use Level In Strong Vs Filter"] = "筛选时考虑等级"
L["When doing a Strong Vs filter, take the level of the pet into account. If a pet is not high enough level to use a Strong Vs ability, do not list the pet.\n\n\124cffffffffNote:\124r A Strong Vs filter is sometimes useful for identifying pets you want to level or capture. This option will hide those pets while the Strong Vs filter is active."] = "进行克制筛选时考虑宠物等级(未达技能等级要求则隐藏).\n\n注意: 此选项会隐藏待升级/捕捉的宠物."
L["Reset Filters On Login"] = "登录时重置筛选"
L["When logging in, start with all pets listed and no filters active."] = "每次登录时清空所有筛选条件."
L["Reset Sort With Filters"] = "重置筛选时恢复排序"
L["When clearing filters, also reset the sort back to the default: Sort by Name, Favorites First."] = "清空筛选时恢复默认排序(名称排序， 最爱优先)."
L["Don't Reset Search With Filters"] = "保留搜索内容"
L["When manually clearing filters, don't clear the search box too.\n\nSome actions, such as logging in or Find Similar, will always clear search regardless of this setting."] = "手动清空筛选时保留搜索框内容(登录/查找相似等操作仍会清空)."
L["Sort By Chosen Name"] = "按自定义名称排序"
L["When pets are sorted by name, sort them by the name given with the Rename option instead of their original name."] = "按重命名后的自定义名称排序."
L["Sort New Pets To Top"] = "新宠物置顶"
L["When you learn new pets, temporarily sort them to the top of the pet list until you next close Rematch or choose Reset All from the filter menu."] = "新获得宠物临时置顶(关闭插件或重置筛选后失效)."
L["Hide Non-Battle Pets"] = "隐藏非战斗宠物"
L["Only list pets that can battle. Do not list pets like balloons, squires and other companion pets that cannot battle."] = "仅显示可战斗宠物(隐藏气球/侍从等)."
L["Allow Hidden Pets"] = "允许隐藏宠物"
L["Allow the ability to hide specific pet species in the pet list with a 'Hide Pet' in the list's right-click menu.\n\nYou can view pets you've hidden from the Other -> Hidden Pets filter."] = "允许通过右键菜单隐藏特定种类宠物(可在其他->隐藏宠物筛选中查看)."
L["When exporting pets from the Export Pets filter menu item, only export a list of pets without details."] = "导出宠物时仅输出名称列表"
L["Don't Sort By Relevance"] = "不按相关性排序"
L["When searching for pets by name, don't sort the results by relevance.\n\nWhen sorted by relevance, pets with the search term in their name are listed first, followed by term in notes, then abilities."] = "名称搜索时不按相关性排序(默认名称>注释>技能)."
L["Breed Options"] = "品种选项"
L["Breed Source"] = "品种来源"
L["Breed Format"] = "品种格式"
L["Pet Card Options"] = "宠物卡片选项"
L["Card Background"] = "卡片背景"
L["Flip Modifier Key"] = "翻转快捷键"
L["Don't Flip On Mouseover"] = "悬停不翻转卡片"
L["When you mouseover the pet icon or type icon at the top of the pet card, don't flip to the back of the card. Instead, flip the card only by clicking the pet or type icon at the top of the pet card; or by the flip modifier key if defined."] = "仅通过点击或快捷键翻转卡片."
L["Allow Pet Cards To Be Pinned"] = "允许固定卡片"
L["When dragging a pet card to another part of the screen, pin the card so all future pet cards display in the same spot, until the pet card is moved again or the unpin button is clicked."] = "拖动卡片可固定显示位置."
L["Always Show Health Bar"] = "始终显示生命条"
L["On the pet card, always display the health bar if a pet can battle and has health. While unchecked, the health bar is only displayed for injured pets."] = "可战斗宠物始终显示生命条(默认仅受伤显示)."
L["Always Show HP/XP Bar Text"] = "始终显示生命/经验数值"
L["On the pet card health and experience bars, keep the status text always visible instead of requiring a mouseover to view."] = "无需悬停即可查看具体数值."
L["Always Hide Possible Breeds"] = "始终隐藏可能品种"
L["When the pet card is not minimized, rather than list possible breeds across the bottom of the pet card, always put the list of possible breeds in the tooltip of the pet's breed stat button.\n\nNote: For uncollected pets that don't have a breed, this means possible breeds will not be visible."] = "当宠物卡片未最小化时不在宠物卡片底部列出可能的品种, 而是将可能的品种列表始终放在宠物品种属性按钮的提示信息中.\n\n注意：对于未收集的没有品种的宠物, 这意味着可能的品种将不可见."
L["Always Use Collected Stat"] = "使用收集统计按钮"
L["When the pet card is not minimized, rather than list collected versions of a pet across the bottom of the pet card, use a collected button alongside other stats to display collected totals. Mouseover of the button will display the list of collected versions of the pet."] = "用按钮替代底部收集列表."
L["Show Expansion On Front"] = "正面显示资料片"
L["Instead of displaying the expansion the pet is from on the back of the pet card, display it on the front alongside other stats."] = "在卡片正面显示资料片来源."
L["Show Strongest Vs Stat"] = "显示克制属性"
L["On the pet card display the top three pet types the pet is strongest against, based on its abilities."] = "显示克制的前三种宠物类型."
L["Show Species IDs Stat"] = "显示物种ID"
L["Display the numerical speciesID as a stat on pet cards."] = "在卡片上显示物种ID."
L["Alternate Lore Font"] = "使用现代字体"
L["Use a more modern-looking font for lore text on the back of the pet card."] = "卡片背面故事文本使用现代字体."
L["Use Pet Cards In Battle"] = "战斗中显示卡片"
L["Use the pet card on the unit frames during a pet battle instead of the default tooltip."] = "替换战斗中的默认宠物提示为卡片."
L["Use Pet Cards For Links"] = "链接显示卡片"
L["Use the pet card when viewing a link of a pet someone else sent you instead of the default link."] = "查看他人发送的宠物链接时显示卡片."
L["Notes Options"] = "注释选项"
L["Keep Notes On Screen"] = "保持注释显示"
L["Don't hide notes when changing tabs or closing Rematch."] = "切换标签页或关闭插件时保持注释可见."
L["Even When Escape Pressed"] = "按ESC键不隐藏"
L["Also don't hide notes when ESCape key is pressed."] = "按下ESC键时不隐藏注释."
L["Show Notes When Teams Load"] = "加载队伍显示注释"
L["When a team with notes is loaded, display the notes for the team."] = "加载带注释队伍时自动显示."
L["Show Notes In Battle"] = "战斗中显示注释"
L["If the loaded team has notes, display and lock the notes when you enter a pet battle."] = "进入战斗时锁定显示队伍注释."
L["Only Once Per Team"] = "每队仅显示一次"
L["Only display notes automatically the first time entering battle, until another team is loaded."] = "每个队伍首次进入战斗时自动显示."
L["Notes Size"] = "注释大小"
L["Ability Tooltip Options"] = "技能提示信息选项"
L["Ability Background"] = "技能背景"
L["Show Ability IDs"] = "显示技能ID"
L["Show the ability ID for the ability being viewed in the ability tooltip."] = "在技能提示信息中显示技能ID."
L["Team Options"] = "队伍选项"
L["Load Healthiest Pets"] = "加载最健康宠物"
L["When a team loads, if any pet is injured or dead and there's another version with more health \124cffffffffand identical stats\124r, load the healthier version.\n\nPets in the leveling queue are exempt from this option.\n\n\124cffffffffNote:\124r This is only when a team loads. It will not automatically swap in healthier pets when you leave battle."] = "自动加载同属性更健康版本(升级队列宠物除外)."
L["Allow Any Version"] = "允许任意版本"
L["Instead of choosing only the healthiest pet with identical stats, choose the healthiest version of the pet regardless of stats."] = "加载最健康宠物(不限制属性相同)."
L["After Battles Or Heals Too"] = "战后/治疗后也生效"
L["Also load healthiest pets after leaving a pet battle or using Revive Battle Pets or Battle Pet Bandage."] = "离开战斗或治疗后自动刷新."
L["Always Show Team Tabs"] = "始终显示队伍标签页"
L["Display Where Teams Dragged"] = "显示拖动位置"
L["When a team is dragged to another group, print in the chat window where the team was moved to."] = "拖动队伍到其他分组时在聊天框提示."
L["Enable Dragging To Move Teams"] = "启用拖动移动队伍"
L["Allow moving teams or groups by dragging them. When this is unchecked you can still move a team or group from its right-click menu."] = "允许通过拖拽移动队伍/分组."
L["Require Click To Drag Teams"] = "需点击确认移动"
L["When dragging teams or groups to move them, release of the mouse button at the end of the drag will not move the team or group. A separate click is needed."] = "拖放后需再次点击确认移动."
L["Prioritize Breed On Import"] = "导入优先品种"
L["When importing or receiving teams, fill the team with the best matched breed as the first priority instead of the highest level."] = "导入队伍时优先匹配品种而非等级."
L["Remember Import Override"] = "记住导入覆盖选项"
L["Rather than resetting to 'Create a new copy' everytime a team is imported and another team shares the same name, remember the last-chosen option without resetting."] = "记住上次导入同名队伍的选择."
L["Random Pet Options"] = "随机宠物选项"
L["Random Pet Rules"] = "随机规则"
L["Pick Aggressive Counters"] = "优先攻击克制"
L["When using a Load Random Pets button for random pets to counter a target, prefer pets with more Strong attacks over pets that are Tough vs opponent attacks."] = "随机宠物时优先高攻击克制."
L["Random Abilities Too"] = "随机技能"
L["For random pets, choose random abilities too."] = "同时随机选择技能."
L["Warn For Pets Below Max Level"] = "未满级警告"
L["Show a warning dialog when a random pet is chosen below level 25. (This is recommended if you're doing Family Familiar achievements with random pets.)\n\nWhen possible, random pets will be from a pool of your max-level pets. However, depending on your collected pets and the other random pet options you've chosen, the random pool may include pets not at max level."] = "选择未满级随机宠物时弹出警告."
L["Team Win Record Options"] = "队伍胜利记录选项"
L["Hide Win Record Text"] = "隐藏胜利记录文字"
L["Hide the win record displayed to the right of each team.\n\nYou can still manually edit a team's win record from its right-click menu and automatic tracking (if enabled) will continue if win records are hidden."] = "隐藏队伍右侧胜利记录(仍可手动编辑)."
L["Auto Track Win Record"] = "自动追踪胜利"
L["At the end of each battle, automatically record whether the loaded team won or lost.\n\nForfeits always count as a loss.\n\nYou can still manually update a team's win record at any time from its right-click menu."] = "战后自动记录胜利(认输计为失败)."
L["For PVP Battles Only"] = "仅PVP战斗"
L["Automatically track whether the loaded team won or lost only in a PVP battle and never for a PVE battle."] = "仅记录PVP战斗结果."
L["Display Win-Loss Instead"] = "显示胜负次数"
L["Instead of displaying the win percentage of a team to the right of the team list, display the total number of wins and losses in the format win-loss.\n\nTeam tabs that are sorted by win record will sort by total wins also."] = "用胜负次数替代胜率显示."
L["Leveling Queue Options"] = "升级队列选项"
L["Show Extra Preferences Button"] = "显示额外偏好按钮"
L["When a leveling slot is loaded, show a preferences button above the loadout panel where pets are slotted, in addition to the one always shown at the top of the queue panel."] = "在宠物栏位上方显示偏好设置按钮."
L["Sort Queue By Pet Name Too"] = "队列按名称排序"
L["When the queue is sorted, sort pets by name also. Otherwise, pets will try to stay in the order they were added to the queue or moved."] = "队列排序时同时按名称排列."
L["Hide Leveling Pet Toast"] = "隐藏升级提示"
L["Don't display the popup 'toast' when a new pet is automatically loaded from the leveling queue."] = "自动加载队列宠物时不弹出提示."
L["Add Fill Queue More Option"] = "添加更多填充选项"
L["In addition to a 'More' button added to the Fill Queue dialog, add a Fill Queue More option to the Queue menu."] = "在队列菜单添加'更多'选项."
L["Prefer Living Pets"] = "优先存活宠物"
L["When loading pets from the queue, skip dead pets and load living ones first."] = "跳过死亡宠物优先加载存活."
L["And At Full Health"] = "且满生命值"
L["Also prefer uninjured pets when loading pets from the queue."] = "同时优先未受伤宠物."
L["Double Click To Send To Top"] = "双击置顶队列"
L["When a pet in the queue panel is double clicked, send it to the top of the queue instead of summoning it."] = "双击队列宠物置顶而非召唤."
L["Add Imported Pets To Queue"] = "导入宠物加入队列"
L["When importing a team, automatically add any chosen pets to the leveling queue if they're below level 25."] = "自动添加导入队伍中未满级宠物到队列."
L["Automatically Level New Pets"] = "自动升级新宠物"
L["When you capture or learn a pet that can level, automatically add it to the leveling queue."] = "自动将新获得的可升级宠物加入队列."
L["Only Pets Without One At 25"] = "仅无满级版本时"
L["Only automatically add pets to the queue when you don't have a version already at 25 or in the queue."] = "当无满级或已在队列中的版本时自动添加."
L["Only Rare Pets"] = "仅品质宠物"
L["Only automatically add rare pets to the leveling queue."] = "仅自动添加品质宠物到队列."
L["Random Pet When Queue Empty"] = "队列空时加载随机宠物"
L["When the queue is empty and a team loads with leveling slots, load a random high-level pet in the leveling slots."] = "队列空时在升级栏位加载随机高等级宠物."
L["Confirmation Options"] = "确认选项"
L["Don't ask for confirmation when hiding a pet.\n\nYou can view hidden pets in the 'Other' pet filter."] = "隐藏宠物时不确认(可在'其他'筛选中查看)."
L["If the pet doesn't belong to any teams, don't ask for confirmation when putting a pet in a cage."] = "未加入队伍的宠物放入笼中时不确认."
L["Don't ask for confirmation when deleting a team."] = "删除队伍时不确认."
L["Don't ask for confirmation when deleting notes from a pet or team."] = "删除注释时不确认."
L["Don't ask for confirmation when filling the queue from the Queue menu."] = "填充队列时不确认."
L["Don't ask to stop the Active Sort in the queue when moving a pet within the queue while it's enabled. Always turn off active sort."] = "移动队列宠物时自动关闭动态排序."
L["Don't ask for confirmation when removing a pet from the leveling queue."] = "移出队列时不确认."
L["Don't Warn About Missing Pets"] = "不提示缺失宠物"
L["Don't display a popup when a team loads and a pet within the team can't be found."] = "加载队伍时缺失宠物不弹窗提示."
L["Don't Remind About Backups"] = "不提醒备份"
L["Don't show a popup offering to backup teams every once in a while. Generally, the popup appears sometime after the number of teams increases by 50."] = "不显示定期备份提醒(通常每新增50个队伍提醒)."
L["Miscellaneous Options"] = "杂项选项"
L["Use Default Journal"] = "使用默认日志"
L["Turn off Rematch integration with the default pet journal.\n\nYou can still use Rematch in its standalone window, accessed via key binding, /rematch command or from the Minimap button if enabled in options."] = "禁用默认宠物日志整合(仍可通过独立窗口使用)."
L["Keep Companion"] = "保持伙伴召唤"
L["After a team is loaded, summon back the companion that was at your side before the load; or dismiss the pet if you had none summoned."] = "加载队伍后恢复之前的伙伴召唤状态."
L["Use Minimap Button"] = "使用小地图按钮"
L["Place a button on the minimap to toggle Rematch and load favorite teams."] = "显示小地图按钮快速访问."
L["No Summon On Double Click"] = "禁用双击召唤"
L["Do nothing when pets within Rematch are double-clicked. The normal behavior of double click throughout Rematch is to summon or dismiss the pet."] = "双击宠物不执行召唤/解散操作."
L["Disable Sharing"] = "禁用分享功能"
L["Disable the Send button and also block any incoming pets sent by others. Import and Export still work."] = "禁用发送/接收队伍功能(导入/导出仍可用)."
L["Help Options"] = "帮助选项"
L["Hide Extra Help"] = "隐藏额外帮助"
L["Hide the informational \"Help\" items found in many menus and on the pet card."] = "隐藏各处的\"帮助\"提示条目."
L["Hide Descriptive Tooltips"] = "隐藏功能说明提示信息"
L["Hide tooltips that describe what a button does."] = "隐藏按钮功能说明."
L["Hide Toolbar Tooltips"] = "隐藏工具栏提示信息"
L["Hide tooltips for the toolbar buttons."] = "隐藏工具栏按钮提示信息."
L["Hide Option Tooltips"] = "隐藏选项提示信息"
L["Hide tooltips for options like the one you're reading now."] = "隐藏选项说明提示信息."
L["Hide Truncated Tooltips"] = "隐藏截断提示信息"
L["Hide tooltips for team or target names when they're truncated (such as Sully \"The Pickle\" McL... instead of Sully \"The Pickle\" McLeary)."] = "名称被截断时不显示完整提示信息."
L["About Rematch"] = "关于Rematch"
L["Version "] = "版本"

-- panels\optionsPanel.lua
L["Search Options"] = "搜索选项"
L["The standalone window can be scaled from 50% to 200% of its normal size:"] = "独立窗口缩放比例(50%-200%):"
L["When the standalone window is minimized or maximized, use the chosen corner/edge as the anchor."] = "最小化/最大化时使用指定锚点位置."
L["Panel Tabs"] = "面板标签"
L["Choose which corner of the standalone Rematch window to anchor panel tabs such as Pets, Teams, Targets, etc.\n\nNote: Choosing a new anchor for the whole window will change the tabs anchor to match. You can change this tabs anchor again anytime."] = "选择面板标签(宠物/队伍/目标等)的停靠位置.\n\n注意: 修改窗口主锚点会同步调整标签位置."
L["Choose how quickly you prefer the tooltips (including pet ability tooltips) to be shown."] = "选择提示信息显示速度(含宠物技能提示)."
L["Tooltip Speed:"] = "提示信息速度:"
L["Slow"] = "慢速"
L["Slow Mouseover"] = "慢速悬停"
L["Wait three quarters of a second for the tooltip to appear when you mouseover a button with a tooltip."] = "悬停0.75秒后显示提示信息."
L["Normal"] = "普通"
L["Normal Mouseover"] = "普通悬停"
L["Wait a quarter of a second for the tooltip to appear when you mouseover a button with a tooltip."] = "悬停0.25秒后显示提示信息."
L["Fast"] = "快速"
L["Fast Mouseover"] = "快速悬停"
L["Immediately show the tooltip when you mouseover a button with a tooltip."] = "悬停立即显示提示信息."
L["Card Speed:"] = "卡片显示速度:"
L["Wait three quarters of a second for the pet card or notes to appear when you mouseover a pet or notes button."] = "悬停0.75秒后显示卡片/注释."
L["Wait a quarter of a second for the pet card or notes to appear when you mouseover a pet or notes button."] = "悬停0.25秒后显示卡片/注释."
L["Immediately show the pet card or notes when you mouseover a pet or notes button."] = "悬停立即显示卡片/注释."
L["On Click"] = "点击显示"
L["Only show the pet card or notes when you click a pet or notes button."] = "点击按钮后显示卡片/注释"
L["The modifier key that will flip the pet card over. Regardless of this setting, you can flip the pet card over by mouseover of the pet's icon at the top of the card."] = "设置翻转卡片的组合键(悬停宠物图标仍可翻转)."
L["The artwork displayed in the background on the front of pet cards."] = "宠物卡片正面背景图案"
L["Expansion Art"] = "资料片艺术"
L["Portrait Art"] = "肖像艺术"
L["Icon Art"] = "图标艺术"
L["Type Art"] = "类型艺术"
L["The artwork displayed in the background of ability tooltips."] = "技能提示信息背景图案."
L["Rules to apply when loading a random pet. The more strict rules will limit the pool of random pets to choose from.\n\nNote: When a team loads with random pets in all three slots, 'Lenient' rules are used regardless of this setting."] = "随机宠物加载规则(更严格规则限制可选范围).\n\n注意: 队伍三栏位全随机时默认使用'宽松'规则."
L["Strict"] = "严格"
L["Scrict Rules"] = "严格规则"
L["When a random pet is chosen, never pick pets saved in a team and never pick injured pets."] = "不选队伍中/受伤的宠物."
L["Normal Rules"] = "普通规则"
L["When a random pet is chosen, prefer pets not saved in a team and prefer uninjured pets."] = "优先未加入队伍/未受伤宠物."
L["Lenient"] = "宽松"
L["Lenient Rules"] = "宽松规则"
L["When a random pet is chosen, allow pets saved in a team and prefer uninjured pets."] = "允许选择队伍中宠物, 优先未受伤."
L["Which enabled addon you want to use to supply breed data."] = "选择提供品种数据的插件."
L["No breed information will be shown if this is selected. Rematch does not maintain its own breed data."] = "选择此项将不显示品种信息."
L["How breeds should display."] = "品种显示方式."
L["Letters"] = "字母"
L["Numbers"] = "数字"
L["Icons"] = "图标"
L["Interact On Target"] = "目标交互方式"
L["Choose the action to take when you target an NPC with a saved team that's not already loaded."] = "选中带保存队伍的NPC时的操作."
L["On Target:"] = "选中目标时:"
L["Do Nothing"] = "无操作"
L["When targeting an NPC with a saved team not already loaded, do nothing."] = "不做任何操作."
L["Prompt To Load"] = "提示加载"
L["When targeting an NPC with a saved team not already loaded, show a prompt to load the save team."] = "显示加载队伍提示."
L["Show Window"] = "显示窗口"
L["When targeting an NPC with a saved team not already loaded, show the standalone Rematch window."] = "显示独立窗口."
L["Auto Load"] = "自动加载"
L["When targeting an NPC with a saved team not already loaded, automatically load the saved team.\n\n%sWarning\124r: If you target with right click and immediately enter battle, it may be too late to load a team. %sAuto Load is not recommended for On Target.\124r Use On Mouseover for Auto Load instead."] = "自动加载队伍(右键选中后立即进入战斗可能失效, 建议使用鼠标悬停自动加载)."
L["Interact On Soft Interact"] = "软交互方式"
L["Choose the action to take when you soft interact with an NPC with a saved team that's not already loaded.\n\n%sNote\124r: This option is only available if SoftTargetInteract cvar is fully enabled (3). It will be hidden otherwise."] = "软交互NPC时的操作(需启用SoftTargetInteract CVar)."
L["On Soft Interact:"] = "软交互时:"
L["When soft interactiong with an NPC with a saved team not already loaded, do nothing."] = "无操作."
L["When soft interacting with an NPC with a saved team not already loaded, show a prompt to load the save team."] = "显示加载提示."
L["When soft interacting with an NPC with a saved team not already loaded, show the standalone Rematch window."] = "显示独立窗口."
L["When soft interacting with an NPC with a saved team not already loaded, automatically load the saved team."] = "自动加载队伍."
L["Interact On Mouseover"] = "鼠标悬停交互"
L["Choose the action to take when the mouse moves over an NPC with a saved team that's not already loaded."] = "鼠标悬停带保存队伍的NPC时的操作."
L["On Mouseover:"] = "鼠标悬停时:"
L["When the mouse moves over an NPC with a saved team not already loaded, do nothing."] = "无操作."
L["When the mouse moves over an NPC with a saved team not already loaded, show a prompt to load the save team."] = "显示加载提示."
L["When the mouse moves over an NPC with a saved team not already loaded, show the standalone Rematch window."] = "显示独立窗口."
L["When the mouse moves over an NPC with a saved team not already loaded, automatically load the saved team."] = "自动加载队伍."
L["Choose the size of the text in the pet and team notes."] = "选择注释文字大小."
L["Small"] = "小"
L["Medium"] = "中"
L["Large"] = "大"
L["Adjust the relative size of the standalone Rematch window by changing its scale."] = "调整独立窗口缩放比例."

-- panels\petsPanel.lua
L["Search Pets"] = "搜索宠物"
L["Max Level Filter"] = "满级筛选"
L["%s Level 25 pets\n%s Level 25 \124cff2090fdrare\124r pets"] = "%s满级宠物\n%s满级\124cff2090fd品质\124r宠物"
L["Pets: %s%d"] = "宠物: %s%d"
L["Filters: %s%s"] = "筛选: %s%s"

-- panels\queuePanel.lua
L["Queue"] = "队列"
L["Leveling Pets: %s%d"] = "升级宠物: %s%d"
L["Active Sort:  %s %s%s"] = "动态排序: %s %s%s"

-- panels\targetsPanel.lua
L["Search Targets"] = "搜索目标"
L["No recent targets"] = "无最近目标"

-- panels\teamsPanel.lua
L["Search Teams"] = "搜索队伍"
L["No favorite teams"] = "无最爱队伍"
L["No ungrouped teams"] = "无未分组队伍"
L["No teams in this group"] = "本组无队伍"

-- process\interact.lua
L["Load this team?"] = "加载此队伍?"
L["This target"] = "此目标"
L["%s has a saved team"] = "%s有保存的队伍"

-- process\loadTeam.lua
L["Pets are missing"] = "宠物缺失"
L["Low level random pet"] = "低等级随机宠物"
L["Pets are missing in the team just loaded."] = "加载的队伍存在缺失宠物."
L["A low level random pet just loaded."] = "加载了低等级随机宠物."

-- process\preferences.lua
L["Current Leveling Preferences"] = "当前升级偏好"
L["Current"] = "当前"
L["Default"] = "默认"
L["Combined team, group and default preferences"] = "综合队伍/分组/默认偏好"
L["Loaded Team's Group Preferences"] = "加载队伍的分组偏好"
L["No saved team loaded"] = "未加载保存队伍"
L["Group preferences are saved to the loaded team's group and override default preferences."] = "分组偏好覆盖默认偏好."
L["Loaded Team Preferences"] = "加载队伍的偏好"
L["Team preferences are saved to the loaded team and override default and group preferences."] = "队伍偏好覆盖分组/默认偏好."
L["Default Preferences"] = "默认偏好"
L["Base preferences regardless of team loaded"] = "基础偏好设置"
L["Default preferences are always active (unless paused) regardless of team loaded."] = "默认偏好始终生效(暂停除外)."
L["Leveling preferences choose which pets are picked first in the leveling queue.\n\n"] = "升级偏好决定队列优先级.\n\n"
L["Current Preferences:"] = "当前偏好:"
L["Minimum level"] = "最低等级"
L["Maximum level"] = "最高等级"
L["Minimum health"] = "最低生命值"
L["  Allow any %s or %s\n"] = "  允许%s或%s\n"
L["  Expected damage taken: %s\n"] = "  预期承受伤害:%s\n"
L["Maximum health"] = "最高生命值"
L["None\n"] = "无\n"
L["Pause"] = "暂停"
L["\n%sPreferences are currently paused. \124rRight-click this button to resume preferences.\n"] = "\n%s偏好当前已暂停. \124r右键恢复偏好设置.\n"
L["Resume"] = "恢复"
L["\n%s %sEdit Preferences\n%s %s Preferences"] = "\n%s %s编辑偏好\n%s %s偏好设置"

-- process\queue.lua
L["%s has also been added to your leveling queue!"] = "%s已被加入升级队列!"

-- process\send.lua
L["Send"] = "发送"
L["Enter the name of an online Rematch user:"] = "输入在线的Rematch用户:"
L["Send To:"] = "发送至:"
L["Sending, please wait..."] = "发送中, 请稍候..."
L["Incoming Rematch Team"] = "收到Rematch队伍"
L["Someone"] = "某人"
L["%s%s has sent you a team!"] = "%s%s发送给你一个队伍!"
L["No response. This player is not online or doesn't have Rematch enabled."] = "无响应. 该玩家不在线或未启用Rematch."
L["Team successfully sent!"] = "队伍发送成功!"
L["They're busy. Try again later."] = "对方繁忙, 请稍后再试."
L["They're in combat. Try again later."] = "对方在战斗中, 请稍后再试."
L["They have team sharing disabled."] = "对方已禁用队伍分享功能."
L["There was an error. Try again later."] = "发生错误, 请稍后再试."

-- process\teamStrings.lua
L["any"] = "任意"
L["at least %d health"] = "至少%d生命值"
L["allow low-level Magic or Mechanical pets"] = "允许低等级魔法/机械宠物"
L["expect %s damage"] = "预计%s伤害"
L["at most %d health"] = "最多%d生命值"
L["at least level %.f"] = "至少%.f级"
L["at most level %.f"] = "最多%.f级"
L["%s has been added to your leveling queue!"] = "%s已被加入升级队列!"
L["Backup Teams"] = "备份队伍"
L["You have %s%d\124r Rematch teams.\n\nWould you like to back them up now?"] = "你有%s%d\124r个Rematch队伍.\n\n是否立即备份?"
L["Choosing Yes will export all teams to copy and paste in an email to yourself or someplace safe.\n\nYou can also do this at any time from the Teams button at the top of the Teams panel of Rematch."] = "选择是将导出所有队伍数据, 可保存至安全位置.\n\n也可随时通过队伍面板顶部按钮操作."

-- process\toast.lua
L["Now leveling:"] = "正在升级:"
L["Rematch's leveling queue is empty"] = "Rematch升级队列为空"
L["All done leveling pets!"] = "宠物升级完毕!"

-- roster\filters.lua
L["Stats"] = "属性"
L["Favorites"] = "最爱"
L["Types"] = "类型"
L["Sources"] = "来源"
L["Similar"] = "相似"
L["Moveset"] = "技能组"
L["Sort"] = "排序"
L["Battle"] = "战斗"
L["Quantity"] = "数量"
L["Notes"] = "注释"
L["Hidden"] = "隐藏"
L["Zone"] = "区域"

-- savedvars\savedGroups.lua
L["Ungrouped Teams"] = "未分组队伍"

-- templates\petListButton.lua
L["This pet cannot level.\n\nIt can't be added to the leveling queue."] = "该宠物无法升级.\n\n无法加入队列."

-- tooltips\abilityTooltip.lua
L["Vs"] = "Vs"
L["\124TInterface\\WorldMap\\Gear_64Grey:16:16:0:0:64:64:8:56:6:57\124t %sAbility ID: %d"] = "\124TInterface\\WorldMap\\Gear_64Grey:16:16:0:0:64:64:8:56:6:57\124t %s技能ID: %d"

-- utils\utils.lua
L["Please Wait..."] = "请稍候..."

-- Version: 5.0.1 --
-- cards\petCard.lua
L["Find Pets With This Ability"] = "查找拥有此技能的宠物"

-- menus\petMenu.lua
L["Start Leveling"] = "开始升级"

-- menus\teamMenu.lua
L["Are you sure you want to delete the group %s and all teams within it?"] = "确定删除分组%s及其所有队伍?"
L["Are you sure you want to delete the group %s? All of its teams will be moved to the %s group."] = "确定删除分组%s?其所有队伍将移至%s分组."

-- panels\optionsList.lua
L["When you interact with an NPC that has more than one team saved to it, choose the team with no injured pets instead of the topmost team for the target. On Prompt To Load and Show Window options where you can choose which team to load before loading, start with the healthiest team."] = "存在多个队伍时优先选择无受伤宠物的队伍."
L["Prefer Minimized Window"] = "优先最小化窗口"
L["When the window is automatically summoned such as from an Interact Option or Safari Hat Reminder, summon the window in minimized mode."] = "自动弹出窗口时默认最小化."
L["Always Use Pet Satchel"] = "始终使用宠物袋"
L["Rather than displaying all toolbar buttons in larger views of the addon, always use the Pet Satchel button to cycle through infrequently used toolbar buttons."] = "通过宠物袋按钮切换不常用工具栏."
L["Hide Breed In Lists"] = "列表中隐藏品种"
L["Hide the breeds displayed in lists. Breeds will still be visible in pet cards."] = "列表中不显示品种(卡片中仍可见)."
L["Hide Breed In Pet Slots"] = "栏位中隐藏品种"
L["Hide the breeds displayed on pet slots. Breeds will still be visible in pet cards."] = "栏位中不显示品种(卡片中仍可见)."

-- Version: 5.0.2 --
-- menus\queueMenu.lua
L["Press Ctrl+C to copy to clipboard"] = "按Ctrl+C复制到剪贴板"

-- panels\optionsList.lua
L["Hide the informational \"Help\" items found in menus, pet cards, dialogs and elsewhere."] = "隐藏所有\"帮助\"提示条目"
L["All Options Troubleshoot Export Reset"] = "所有选项 | 故障排除 | 导出 | 重置"

-- panels\optionsPanel.lua
L["Export Options"] = "导出选项"
L["This is intended to help troubleshoot issues.\n\nMany options interact with other options. When reporting a problem this can help recreate the issue."] = "用于故障排除(导出选项可能相互影响)."
L["Reset Options"] = "重置选项"
L["Restore all options to default?"] = "恢复所有选项为默认值?"
L["This will restore all options in Rematch to default values and reload the UI.\n\nThis includes all settings in the Options panel but does not include teams, leveling queue or notes."] = "重置所有选项并重载界面(不影响队伍/队列/注释)."
L["All Options:"] = "所有选项:"
L["Reset"] = "重置"
L["Export"] = "导出"

-- Version: 5.0.4 --
-- chrome\toolbar.lua
L["Unique Pets: %s%d\124r\nTotal Pets: %s%d\124r\nUncollected Pets: %s%d\124r\nAverage Level: %s%.1f\124r%s"] = "唯一宠物: %s%d\124r\n总宠物: %s%d\124r\n未收集: %s%d\124r\n平均等级: %s%.1f\124r%s"

-- menus\teamMenu.lua
L["Teams and Groups"] = "队伍与分组"
L["Teams can be organized into an unlimited number of collapsible groups. You can create new groups with %sCreate New Group\124r in this menu. Up to %d groups can be shown as tabs to act as bookmarks to these groups.\n\nBoth teams and groups can be rearranged with drag and drop. To easily move many teams to another group, use %sTeam Herder\124r in this menu.\n\nTeams with a %s beside their name contain at least one target.\nTeams with a %s beside their name contain a leveling preference.\nPets or targets with a %s beside their name belong to at least one team."] = "队伍可组织为可折叠分组(最多显示%d个标签页).\n\n拖拽调整顺序, 使用队伍管理批量移动.\n\n%s: 包含目标\n%s: 包含升级偏好\n%s: 属于某队伍."

-- panels\optionsList.lua
L["Show Create New Group Tab"] = "显示新建分组标签"
L["When space permits, add a button at the bottom of team tabs to create a new group."] = "在标签页底部添加新建分组按钮."
L["Show team tabs along the right side of the window even if you're not on the teams panel."] = "始终显示队伍标签页."
L["Never Show Team Tabs"] = "永不显示队伍标签页"
L["Never show team tabs along the right side of the window even if you're on the teams panel."] = "即使处于队伍面板也不显示标签页."
L["Target or pet is in a team"] = "目标/宠物在队伍中"
L["Pet is in the leveling queue"] = "宠物在升级队列中"
L["Team or pet has notes"] = "队伍/宠物有注释"
L["Team has at least one target"] = "队伍包含目标"
L["Team or group has preferences"] = "队伍/分组有偏好设置"

-- panels\optionsPanel.lua
L["Import Options"] = "导入选项"
L["This will reset most options, set them to values pasted here, then reload the UI. %sUse this at your own risk!\124r Tinkering with these values can cause Rematch to become unstable and require a full reset."] = "导入选项可能引发不稳定, 需谨慎操作!"
L["This will reset most options!\nThis cannot be undone!"] = "将重置大部分选项!\n不可撤销!"

-- Version: 5.0.5 --
-- panels\optionsList.lua
L["Hide Notes Button In Battle"] = "战斗中隐藏注释按钮"
L["In the Battle UI, hide the notes \"micro\" button to show notes for the currently-loaded team. Enable this option if another addon wants to use the same space."] = "隐藏战斗界面中的注释\"宏\"按钮(避免与其他插件冲突)."
L["When the queue is empty and a team loads with leveling slots, put random pets that are not max level into the leveling slots."] = "队列空时填充未满级随机宠物."
L["Pick Random Max Level"] = "选择满级随机宠物"
L["When the queue is empty and a team loads with leveling slots, put random max-level pets in the leveling slots."] = "队列空时填充满级随机宠物."

-- Version: 5.1.0 --
-- chrome\toolbarButtons.lua
L["Safari Hat"] = "狩猎帽"

-- dialogs\dialogMixins.lua
L["Top %d Winning Teams"] = "胜率前%d队伍"

-- dialogs\summaryDialog.lua
L["Rank teams by percentage won"] = "按胜率排行队伍"
L["Pet Types"] = "宠物类型"
L["Battles"] = "战斗"

-- main\constants.lua
L["Pet Tags are a way to categorize pets for any meaning you choose. You can then filter by specific tags.\n\nTo tag a pet, right-click a pet in the pet list and choose a tag from the Pet Tags menu.\n\nTo easily tag multiple pets, choose the %sPet Herder\124r option in the main Filters menu.\n\nYou can rename a tag by moving the mouse over a tag in a Pet Tags menu and clicking the %s that appears to the right of the tag's name.\n\nFor instance you can rename %s to Wild Pets To Get, tag pets you'd like to capture with a %s, and the pet card and other places will use the new name for the tag."] = "宠物标签功能说明: 右键宠物选择标签, 使用宠物管理批量操作， 悬停标签可重命名."

-- menus\petFilterMenu.lua
L["Pet Tags"] = "宠物标签"
L["Pet Herder"] = "宠物管理"

-- panels\optionsList.lua
L["Badge Options"] = "标记选项"
L["Only Show Badges On Mouseover"] = "悬停显示标记"
L["Hide all badges unless the mouse is over the pet, team or target.\n\nA badge is a non-interactive icon to the right of a list item to indicate some property such as whether it's leveling.\n\nWith this option enabled, the notes button, breed and win record are also hidden unless the mouse is over the list item."] = "仅悬停时显示标记(含注释按钮/品种/胜率)."
L["Hide Team Badges %s"] = "隐藏队伍标记%s"
L["Hide the %s badge on pets and targets that indicate the pet or target is saved in a team."] = "隐藏表示宠物/目标在队伍中的%s标记."
L["Hide Leveling Badges %s"] = "隐藏升级标记%s"
L["Hide the %s badge on pets that indicate the pet is in the leveling queue."] = "隐藏表示宠物在队列中的%s标记."
L["Hide Pet Tag Badges %s"] = "隐藏宠物标签标记%s"
L["Hide the pet tag badges (such as %s %s %s etc) on pets to indicate what pet tag has been given to the pet."] = "隐藏宠物标签标记(如%s %s %s等)."
L["Hide Target Badges %s"] = "隐藏目标标记%s"
L["Hide the %s badge on teams that indicate the team contains a target."] = "隐藏表示队伍包含目标的%s标记."
L["Hide Preference Badges %s"] = "隐藏偏好标记%s"
L["Hide the %s badge on teams that indicate the team contains leveling preferences."] = "隐藏表示队伍有升级偏好的%s标记."
L["Hide Notes Badges %s"] = "隐藏注释标记%s"
L["Hide the %s badge/button on pets and teams that indicate the pet or team has saved notes."] = "隐藏表示有注释的%s标记/按钮."
L["Hide External Badges %s"] = "隐藏外部标记%s"
L["Try to hide any badges added to lists from an external source like a third-party addon. (Rematch has no control over what outside addons do, so some addon's badges may not hide with this option.)"] = "尝试隐藏第三方插件添加的标记(可能不兼容)."
L["Larger Breed Text"] = "放大品种文字"
L["Increase the size of breed text (such as B/B or H/P) on pet list buttons and pet slots."] = "增大品种文字(如B/B或H/P)的显示尺寸."
L["Combine Group Key"] = "合并分组快捷键"
L["Don't Ask To Remove From Queue"] = "移出队列时不询问"

-- panels\optionsPanel.lua
L["While dragging a team group in the team list, holding this modifier key when you click another group will combine the two groups by moving all teams in the group on the cursor into the clicked group."] = "拖动分组时按住组合键点击另一分组合并."

-- process\dragFrame.lua
L["Combine Groups"] = "合并分组"
L["Combine team groups?"] = "确定合并分组?"
L["This will move all teams from %s to %s, leaving the %s group empty."] = "将%s所有队伍移至%s, 清空%s分组."
L["This will move all teams from %s to %s and then delete the emptied %s group afterwards."] = "移动队伍后删除空分组%s."
L["Don't Delete Empty Group"] = "不删除空分组"
L["You can also selectively move many teams with the Team Herder tool from the Teams button"] = "也可使用队伍管理工具选择性移动队伍."

-- process\petHerder.lua
L["Now click on pets in the pet list to use this action on the pets"] = "点击宠物列表应用此操作"
L["Pick an action to use on multiple pets"] = "选择批量操作"
L["Then click on pets in the pet list to use this action on the pets"] = "随后点击宠物执行操作"
L["Allow caging pets in a team"] = "允许笼养队伍中的宠物"
L["When the cursor changes to a \124TInterface\\Cursor\\Crosshairs:16\124t over a pet, click the pet to use the chosen action"] = "当光标变为\124TInterface\\Cursor\\Crosshairs:16\124t时点击宠物执行操作"
L["You don't own this pet"] = "未拥有该宠物"
L["Injured pets can't be caged"] = "受伤宠物无法放入笼中"
L["Slotted pets can't be caged"] = "已装备宠物无法放入笼中"
L["This pet is not tradable"] = "该宠物不可交易"
L["This pet is in a team"] = "宠物在队伍中"
L["This pet can't level"] = "该宠物无法升级"
L["This pet has no pet tag"] = "宠物未设置标签"

-- utils\utils.lua
L["Cage Pet (Without Confirmation)"] = "放入笼中(无需确认)"
L["Set/Remove Favorite"] = "设置/移除最爱"
L["Add/Remove From Leveling Queue"] = "加入/移出升级队列"
L["Remove Pet Tags"] = "移除宠物标签"
L["Set/Remove Pet Tag: %s"] = "设置/移除标签: %s"

-- Version: 5.1.2 --
-- menus\teamMenu.lua
L["This is a system group that cannot be deleted."] = "系统分组无法删除."
L["Delete Teams"] = "删除队伍"
L["This group has no teams."] = "该分组无队伍."
L["Delete Group Teams"] = "删除分组队伍"
L["There are %s%d\124r teams in the group %s."] = "分组%s中共有%s%d\124r个队伍."
L["%sAre you sure you want to %sdelete\124r these teams? This cannot be undone."] = "%s确定要删除这些队伍吗? 不可撤销."

-- panels\optionsList.lua
L["Mousewheel Speed"] = "滚轮速度"
L["Choose how quickly you prefer lists to scroll when you mousewheel up or down over a list."] = "选择列表滚轮滚动速度."
L["Slow Mousewheel"] = "慢速滚动"
L["Scroll one line at a time."] = "每次滚动一行."
L["Normal Mousewheel"] = "普通滚动"
L["Scroll two lines at a time."] = "每次滚动两行."
L["Medium Mousewheel"] = "中速滚动"
L["Scroll roughly half a page at a time."] = "每次滚动半页."
L["Fast Mousewheel"] = "快速滚动"
L["Scroll nearly a whole page at a time."] = "每次滚动整页."
L["Battle Pet Breed ID"] = "战斗宠物品种ID"
L["PetTracker"] = "PetTracker"

end